--------------------------------------------------------
--  颇老捞 积己凳 - 格夸老-7岿-13-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMIN_TB
--------------------------------------------------------

  CREATE TABLE "KORAIL"."ADMIN_TB" 
   (	"ADMINNO" VARCHAR2(4 BYTE), 
	"ADMINID" VARCHAR2(15 BYTE), 
	"ADMINPW" VARCHAR2(1000 BYTE), 
	"ADMINNAME" VARCHAR2(20 BYTE), 
	"ADMINGRADE" VARCHAR2(10 BYTE) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into KORAIL.ADMIN_TB
SET DEFINE OFF;
Insert into KORAIL.ADMIN_TB (ADMINNO,ADMINID,ADMINPW,ADMINNAME,ADMINGRADE) values ('001','admin','admin123','包府磊','0');
Insert into KORAIL.ADMIN_TB (ADMINNO,ADMINID,ADMINPW,ADMINNAME,ADMINGRADE) values ('002','admin1','admin123','包府磊1','0');
Insert into KORAIL.ADMIN_TB (ADMINNO,ADMINID,ADMINPW,ADMINNAME,ADMINGRADE) values ('003','admin2','admin123','包府磊','0');
Insert into KORAIL.ADMIN_TB (ADMINNO,ADMINID,ADMINPW,ADMINNAME,ADMINGRADE) values ('004','admin3','admin123','包府磊','0');
Insert into KORAIL.ADMIN_TB (ADMINNO,ADMINID,ADMINPW,ADMINNAME,ADMINGRADE) values ('005','admin4','admin123','包府磊','0');
Insert into KORAIL.ADMIN_TB (ADMINNO,ADMINID,ADMINPW,ADMINNAME,ADMINGRADE) values ('006','admin5','admin123','包府磊','0');
--------------------------------------------------------
--  DDL for Index SYS_C0012908
--------------------------------------------------------

  CREATE UNIQUE INDEX "KORAIL"."SYS_C0012908" ON "KORAIL"."ADMIN_TB" ("ADMINNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ADMIN_TB
--------------------------------------------------------

  ALTER TABLE "KORAIL"."ADMIN_TB" MODIFY ("ADMINNO" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."ADMIN_TB" MODIFY ("ADMINID" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."ADMIN_TB" MODIFY ("ADMINPW" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."ADMIN_TB" MODIFY ("ADMINNAME" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."ADMIN_TB" MODIFY ("ADMINGRADE" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."ADMIN_TB" ADD PRIMARY KEY ("ADMINNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
