--------------------------------------------------------
--  파일이 생성됨 - 목요일-7월-13-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table KTXRATEINFO_TB
--------------------------------------------------------

  CREATE TABLE "KORAIL"."KTXRATEINFO_TB" 
   (	"TRAINNO" NUMBER, 
	"ADMINNO" VARCHAR2(4 BYTE), 
	"SEATDIVISION" VARCHAR2(60 BYTE), 
	"ADULTRATE" VARCHAR2(7 BYTE), 
	"CHILDRATE" VARCHAR2(7 BYTE), 
	"SENIORRATE" VARCHAR2(7 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into KORAIL.KTXRATEINFO_TB
SET DEFINE OFF;
Insert into KORAIL.KTXRATEINFO_TB (TRAINNO,ADMINNO,SEATDIVISION,ADULTRATE,CHILDRATE,SENIORRATE) values (4,'001','일반','83700','53800','65800');
Insert into KORAIL.KTXRATEINFO_TB (TRAINNO,ADMINNO,SEATDIVISION,ADULTRATE,CHILDRATE,SENIORRATE) values (5,'001','특실','59800','29900','41900');
--------------------------------------------------------
--  DDL for Index SYS_C0012951
--------------------------------------------------------

  CREATE UNIQUE INDEX "KORAIL"."SYS_C0012951" ON "KORAIL"."KTXRATEINFO_TB" ("TRAINNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table KTXRATEINFO_TB
--------------------------------------------------------

  ALTER TABLE "KORAIL"."KTXRATEINFO_TB" MODIFY ("TRAINNO" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."KTXRATEINFO_TB" MODIFY ("ADMINNO" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."KTXRATEINFO_TB" MODIFY ("SEATDIVISION" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."KTXRATEINFO_TB" MODIFY ("ADULTRATE" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."KTXRATEINFO_TB" MODIFY ("CHILDRATE" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."KTXRATEINFO_TB" MODIFY ("SENIORRATE" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."KTXRATEINFO_TB" ADD PRIMARY KEY ("TRAINNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
