--------------------------------------------------------
--  파일이 생성됨 - 목요일-7월-13-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table NOTICE_TB
--------------------------------------------------------

  CREATE TABLE "KORAIL"."NOTICE_TB" 
   (	"NOTICENO" NUMBER, 
	"ADMINNO" VARCHAR2(4 BYTE), 
	"ADMINNAME" VARCHAR2(20 BYTE), 
	"NOTICETITLE" VARCHAR2(200 BYTE), 
	"NOTICEREGDATE" DATE DEFAULT SYSDATE, 
	"NOTICEATTACHMENTS" VARCHAR2(100 BYTE) DEFAULT 'N', 
	"NOTICEETC" VARCHAR2(1 BYTE) DEFAULT '0', 
	"NOTICECONTENT" CLOB DEFAULT empty_clob()
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("NOTICECONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into KORAIL.NOTICE_TB
SET DEFINE OFF;
Insert into KORAIL.NOTICE_TB (NOTICENO,ADMINNO,ADMINNAME,NOTICETITLE,NOTICEREGDATE,NOTICEATTACHMENTS,NOTICEETC) values (21,'001','관리자','코레일 홈페이지(www.korail.com)와 코레일톡 로그인 비밀번호 변경안내',to_date('17/07/06','RR/MM/DD'),'N','0');
Insert into KORAIL.NOTICE_TB (NOTICENO,ADMINNO,ADMINNAME,NOTICETITLE,NOTICEREGDATE,NOTICEATTACHMENTS,NOTICEETC) values (28,'001','관리자','철도노조 파업에 따른 일부 열차 운행중지 알림(12월 1일~12월 8일)/ 재공지12.1.',to_date('17/07/06','RR/MM/DD'),'board_1499348160697_열차시간표.jpg','0');
Insert into KORAIL.NOTICE_TB (NOTICENO,ADMINNO,ADMINNAME,NOTICETITLE,NOTICEREGDATE,NOTICEATTACHMENTS,NOTICEETC) values (27,'001','관리자','전차선 이물질 신고하고, 문화상품권 받자!',to_date('17/07/06','RR/MM/DD'),'N','0');
Insert into KORAIL.NOTICE_TB (NOTICENO,ADMINNO,ADMINNAME,NOTICETITLE,NOTICEREGDATE,NOTICEATTACHMENTS,NOTICEETC) values (29,'001','관리자','IC카드 우선결제(거래) 시행 알림',to_date('17/07/06','RR/MM/DD'),'N','0');
Insert into KORAIL.NOTICE_TB (NOTICENO,ADMINNO,ADMINNAME,NOTICETITLE,NOTICEREGDATE,NOTICEATTACHMENTS,NOTICEETC) values (30,'001','관리자','서울역, 용산역 KTX 모두정차 안내',to_date('17/07/06','RR/MM/DD'),'board_1499349435606_ktx이용.jpg','0');
Insert into KORAIL.NOTICE_TB (NOTICENO,ADMINNO,ADMINNAME,NOTICETITLE,NOTICEREGDATE,NOTICEATTACHMENTS,NOTICEETC) values (31,'001','관리자','레일플러스 제휴 롯데DC패스카드 상품 안내(1522-1822)',to_date('17/07/06','RR/MM/DD'),'board_1499349831962_롯데카드.jpg','0');
Insert into KORAIL.NOTICE_TB (NOTICENO,ADMINNO,ADMINNAME,NOTICETITLE,NOTICEREGDATE,NOTICEATTACHMENTS,NOTICEETC) values (22,'001','관리자','도시락 예약ㆍ배달 서비스를 제공합니다.',to_date('17/07/06','RR/MM/DD'),'board_1499347605496_도시락.jpg','0');
Insert into KORAIL.NOTICE_TB (NOTICENO,ADMINNO,ADMINNAME,NOTICETITLE,NOTICEREGDATE,NOTICEATTACHMENTS,NOTICEETC) values (33,'001','관리자','2016 교통시장조사 경품 당첨자 안내',to_date('17/07/06','RR/MM/DD'),'board_1499653308451_경품이미지.jpg','0');
Insert into KORAIL.NOTICE_TB (NOTICENO,ADMINNO,ADMINNAME,NOTICETITLE,NOTICEREGDATE,NOTICEATTACHMENTS,NOTICEETC) values (32,'001','관리자','2016년 동계 내일로티켓 운영계획 알림',to_date('17/07/06','RR/MM/DD'),'N','0');
Insert into KORAIL.NOTICE_TB (NOTICENO,ADMINNO,ADMINNAME,NOTICETITLE,NOTICEREGDATE,NOTICEATTACHMENTS,NOTICEETC) values (39,'001','관리자','광명역-사당역 KTX 셔틀버스 운행개시 (1월 11일 운행)',to_date('17/07/10','RR/MM/DD'),'board_1499821045479_ProdDisplay_201705190548099070.png','1');
Insert into KORAIL.NOTICE_TB (NOTICENO,ADMINNO,ADMINNAME,NOTICETITLE,NOTICEREGDATE,NOTICEATTACHMENTS,NOTICEETC) values (35,'001','관리자','제1회 초단편 철도영화 공모전 (`17. 5. 01. ~ 7. 31.) / 기간연장',to_date('17/07/09','RR/MM/DD'),'board_1499576625320_ProdDisplay_201706221011570060.png','1');
Insert into KORAIL.NOTICE_TB (NOTICENO,ADMINNO,ADMINNAME,NOTICETITLE,NOTICEREGDATE,NOTICEATTACHMENTS,NOTICEETC) values (36,'001','관리자','코레일의 사랑여행 프로젝트 - 50%특가 사랑여행 KTX 묶음상품 출시',to_date('17/07/09','RR/MM/DD'),'board_1499577112679_ProdDisplay_201706260610169200.png','1');
Insert into KORAIL.NOTICE_TB (NOTICENO,ADMINNO,ADMINNAME,NOTICETITLE,NOTICEREGDATE,NOTICEATTACHMENTS,NOTICEETC) values (37,'001','관리자','똑똑해진 코레일톡 ios 서비스 오픈',to_date('17/07/09','RR/MM/DD'),'board_1499577190206_ProdDisplay_201706270500075130.png','1');
--------------------------------------------------------
--  DDL for Index SYS_C0012937
--------------------------------------------------------

  CREATE UNIQUE INDEX "KORAIL"."SYS_C0012937" ON "KORAIL"."NOTICE_TB" ("NOTICENO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table NOTICE_TB
--------------------------------------------------------

  ALTER TABLE "KORAIL"."NOTICE_TB" MODIFY ("NOTICENO" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."NOTICE_TB" MODIFY ("ADMINNO" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."NOTICE_TB" MODIFY ("ADMINNAME" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."NOTICE_TB" MODIFY ("NOTICETITLE" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."NOTICE_TB" MODIFY ("NOTICEREGDATE" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."NOTICE_TB" MODIFY ("NOTICEATTACHMENTS" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."NOTICE_TB" MODIFY ("NOTICEETC" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."NOTICE_TB" ADD PRIMARY KEY ("NOTICENO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "KORAIL"."NOTICE_TB" MODIFY ("NOTICECONTENT" NOT NULL ENABLE);
