--------------------------------------------------------
--  파일이 생성됨 - 목요일-7월-13-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QNA_TB
--------------------------------------------------------

  CREATE TABLE "KORAIL"."QNA_TB" 
   (	"QNANO" NUMBER, 
	"USERNO" NUMBER, 
	"ADMINNO" VARCHAR2(4 BYTE) DEFAULT '001', 
	"POSTNO" NUMBER, 
	"QNAWRITER" VARCHAR2(30 BYTE), 
	"QNAREGDATE" DATE DEFAULT SYSDATE, 
	"QNATITLE" VARCHAR2(100 BYTE), 
	"QNACONTENT" VARCHAR2(4000 BYTE), 
	"QNAATTACHMENTS" VARCHAR2(100 BYTE) DEFAULT 'N', 
	"ISPUBLIC" VARCHAR2(1 BYTE) DEFAULT '0'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into KORAIL.QNA_TB
SET DEFINE OFF;
Insert into KORAIL.QNA_TB (QNANO,USERNO,ADMINNO,POSTNO,QNAWRITER,QNAREGDATE,QNATITLE,QNACONTENT,QNAATTACHMENTS,ISPUBLIC) values (2,2,'001',null,'성승열',to_date('17/07/04','RR/MM/DD'),'승차권 발권을 못했어요','<p>승차권 발권을 못했어요</p>
','N','0');
Insert into KORAIL.QNA_TB (QNANO,USERNO,ADMINNO,POSTNO,QNAWRITER,QNAREGDATE,QNATITLE,QNACONTENT,QNAATTACHMENTS,ISPUBLIC) values (3,2,'001',null,'성승열',to_date('17/07/04','RR/MM/DD'),'예약 발권 및 반환시간 어떻게 되요?','<p>asdasd</p>
','N','0');
Insert into KORAIL.QNA_TB (QNANO,USERNO,ADMINNO,POSTNO,QNAWRITER,QNAREGDATE,QNATITLE,QNACONTENT,QNAATTACHMENTS,ISPUBLIC) values (4,2,'001',null,'성승열',to_date('17/07/04','RR/MM/DD'),'ios 어플 어디서 받나요?','<p>asdasd</p>
','N','0');
Insert into KORAIL.QNA_TB (QNANO,USERNO,ADMINNO,POSTNO,QNAWRITER,QNAREGDATE,QNATITLE,QNACONTENT,QNAATTACHMENTS,ISPUBLIC) values (5,2,'001',25,'성승열',to_date('17/07/04','RR/MM/DD'),'당첨자는 어떻게 수령해요?','<p>asdasdasd</p>
','N','0');
Insert into KORAIL.QNA_TB (QNANO,USERNO,ADMINNO,POSTNO,QNAWRITER,QNAREGDATE,QNATITLE,QNACONTENT,QNAATTACHMENTS,ISPUBLIC) values (6,2,'001',24,'성승열',to_date('17/07/04','RR/MM/DD'),'예약 취소는 어디서 해야하나요??','<p>예약 취소는 어디서 해야하나요??</p>
','board_1499652497121_ic_seat_left.png','0');
Insert into KORAIL.QNA_TB (QNANO,USERNO,ADMINNO,POSTNO,QNAWRITER,QNAREGDATE,QNATITLE,QNACONTENT,QNAATTACHMENTS,ISPUBLIC) values (11,2,'001',12,'성승열',to_date('17/07/06','RR/MM/DD'),'승차권에 조회 안되는 내역이 있어요','<p>크어헝크헝으허엉</p>
','N','0');
Insert into KORAIL.QNA_TB (QNANO,USERNO,ADMINNO,POSTNO,QNAWRITER,QNAREGDATE,QNATITLE,QNACONTENT,QNAATTACHMENTS,ISPUBLIC) values (13,2,'001',9,'관리자',to_date('17/07/06','RR/MM/DD'),'으랑흐허어흐어엉','<p>흐규흐규흑</p>
','N','0');
Insert into KORAIL.QNA_TB (QNANO,USERNO,ADMINNO,POSTNO,QNAWRITER,QNAREGDATE,QNATITLE,QNACONTENT,QNAATTACHMENTS,ISPUBLIC) values (9,2,'001',13,'성승열',to_date('17/07/05','RR/MM/DD'),'코레일톡이용에 불편한점이 있습니다.','<p>으허헝엉긍엉</p>
','N','0');
Insert into KORAIL.QNA_TB (QNANO,USERNO,ADMINNO,POSTNO,QNAWRITER,QNAREGDATE,QNATITLE,QNACONTENT,QNAATTACHMENTS,ISPUBLIC) values (10,2,'001',null,'성승열',to_date('17/07/05','RR/MM/DD'),'무통장으로 입금했는데 결제 확인은 어떻게 해야하나요?','<p>으어거어허거어컥</p>
','N','1');
Insert into KORAIL.QNA_TB (QNANO,USERNO,ADMINNO,POSTNO,QNAWRITER,QNAREGDATE,QNATITLE,QNACONTENT,QNAATTACHMENTS,ISPUBLIC) values (12,2,'001',11,'관리자',to_date('17/07/06','RR/MM/DD'),'크어헝크헝으허엉','<p>크헝크허엉크허허허헝</p>
','N','0');
Insert into KORAIL.QNA_TB (QNANO,USERNO,ADMINNO,POSTNO,QNAWRITER,QNAREGDATE,QNATITLE,QNACONTENT,QNAATTACHMENTS,ISPUBLIC) values (14,2,'001',15,'성승열',to_date('17/07/06','RR/MM/DD'),'스마트폰 승차권이 뭔가요?','<p>쿠어쿠어쿠어어어헝</p>
','N','0');
Insert into KORAIL.QNA_TB (QNANO,USERNO,ADMINNO,POSTNO,QNAWRITER,QNAREGDATE,QNATITLE,QNACONTENT,QNAATTACHMENTS,ISPUBLIC) values (15,2,'001',14,'관리자',to_date('17/07/06','RR/MM/DD'),'쿠어쿠어쿠어어어헝','<p>123123</p>
','N','0');
Insert into KORAIL.QNA_TB (QNANO,USERNO,ADMINNO,POSTNO,QNAWRITER,QNAREGDATE,QNATITLE,QNACONTENT,QNAATTACHMENTS,ISPUBLIC) values (25,2,'001',5,'관리자',to_date('17/07/10','RR/MM/DD'),'당첨자는 어떻게 수령해요?','<p>알아서 해요~</p>
','board_1499674063505_photo-1484244233201-29892afe6a2c.jpg','0');
Insert into KORAIL.QNA_TB (QNANO,USERNO,ADMINNO,POSTNO,QNAWRITER,QNAREGDATE,QNATITLE,QNACONTENT,QNAATTACHMENTS,ISPUBLIC) values (21,42,'001',16,'관리자',to_date('17/07/06','RR/MM/DD'),'렛츠고 코레일','<p>asd</p>
','board_1499673714941_photo-1484244233201-29892afe6a2c.jpg','0');
Insert into KORAIL.QNA_TB (QNANO,USERNO,ADMINNO,POSTNO,QNAWRITER,QNAREGDATE,QNATITLE,QNACONTENT,QNAATTACHMENTS,ISPUBLIC) values (24,2,'001',6,'관리자',to_date('17/07/10','RR/MM/DD'),'예약 취소는 어디서 해야하나요??','<p>몰라요~</p>
','board_1499674041480_photo-1484244233201-29892afe6a2c.jpg','0');
--------------------------------------------------------
--  DDL for Index SYS_C0013653
--------------------------------------------------------

  CREATE UNIQUE INDEX "KORAIL"."SYS_C0013653" ON "KORAIL"."QNA_TB" ("QNANO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table QNA_TB
--------------------------------------------------------

  ALTER TABLE "KORAIL"."QNA_TB" MODIFY ("QNANO" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."QNA_TB" MODIFY ("USERNO" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."QNA_TB" MODIFY ("ADMINNO" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."QNA_TB" MODIFY ("QNAWRITER" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."QNA_TB" MODIFY ("QNAREGDATE" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."QNA_TB" MODIFY ("QNATITLE" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."QNA_TB" MODIFY ("QNACONTENT" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."QNA_TB" MODIFY ("QNAATTACHMENTS" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."QNA_TB" MODIFY ("ISPUBLIC" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."QNA_TB" ADD PRIMARY KEY ("QNANO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
