--------------------------------------------------------
--  파일이 생성됨 - 목요일-7월-13-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SEAT_TB
--------------------------------------------------------

  CREATE TABLE "KORAIL"."SEAT_TB" 
   (	"SEATNO" NUMBER, 
	"SEATDIVISION" VARCHAR2(60 BYTE), 
	"SEATROW" NUMBER, 
	"SEATCOLUMN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into KORAIL.SEAT_TB
SET DEFINE OFF;
Insert into KORAIL.SEAT_TB (SEATNO,SEATDIVISION,SEATROW,SEATCOLUMN) values (2,'일반',4,15);
Insert into KORAIL.SEAT_TB (SEATNO,SEATDIVISION,SEATROW,SEATCOLUMN) values (3,'특실',3,11);
--------------------------------------------------------
--  DDL for Index SYS_C0012943
--------------------------------------------------------

  CREATE UNIQUE INDEX "KORAIL"."SYS_C0012943" ON "KORAIL"."SEAT_TB" ("SEATNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012944
--------------------------------------------------------

  CREATE UNIQUE INDEX "KORAIL"."SYS_C0012944" ON "KORAIL"."SEAT_TB" ("SEATDIVISION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SEAT_TB
--------------------------------------------------------

  ALTER TABLE "KORAIL"."SEAT_TB" MODIFY ("SEATNO" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."SEAT_TB" MODIFY ("SEATDIVISION" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."SEAT_TB" MODIFY ("SEATROW" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."SEAT_TB" MODIFY ("SEATCOLUMN" NOT NULL ENABLE);
 
  ALTER TABLE "KORAIL"."SEAT_TB" ADD PRIMARY KEY ("SEATNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "KORAIL"."SEAT_TB" ADD UNIQUE ("SEATDIVISION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
